Algoritmo "filho"

Var
 filhos,i:inteiro
salario,media,soma,dividir:real

Inicio

para i:=1 ate 5 faca
escreval("Informe o número de filhos")
leia(filhos)
escreval("Informe o seu salário")
leia(salario)
soma <-salario+salario
dividir <- filhos+filhos/2
fimpara

escreval("A média do salário da população é",soma)
escreval("A média do número de filhos é",dividir)
escreval("O maior salário",salario)

Fimalgoritmo